# Generated by Django 3.2.4 on 2021-07-12 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_scanning_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scan_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='scanning_pics'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Scanning',
        ),
    ]
